language: node_js
dist: trusty
sudo: false
node_js:
- '6'
services:
- rabbitmq
- npm install
- pip install -r requirements.pip --user
before_script:
- npm install -g grunt-cli
- export PATH=$PATH:$HOME/.local/bin DEBUG=fbp-spec:*
env:
  matrix:
  - MSGFLO_BROKER=amqp://localhost
