language: node_js
node_js:
- '6'
addons:
  apt:
    packages:
    - pkg-config
    - cmake
    - openssl
    - libc-ares-dev
before_install:
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
install:
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
- pip install -r requirements.pip --user
before_script:
- mosquitto -d > /dev/null
- npm install -g grunt-cli
- export PATH=$PATH:$HOME/.local/bin
after_script:
- killall mosquitto
