language: node_js
node_js:
- '6'
before_install:
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
install:
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
- pip install msgflo
before_script:
- mosquitto -d
- npm install -g grunt-cli
after_script:
- killall mosquitto
